name: Chromatic Visual Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel in-progress runs on new pushes to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    
    # Skip draft PRs and dependabot PRs
    if: github.event.pull_request.draft == false && !startsWith(github.head_ref, 'dependabot/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for Chromatic to work properly

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Storybook
        run: echo "⚠️ Storybook build temporarily disabled due to package removal"
        continue-on-error: true
        env:
          NODE_ENV: production

      - name: Run Chromatic
        run: echo "⚠️ Chromatic testing temporarily disabled due to Storybook package removal"
        continue-on-error: true

      - name: Comment PR with Chromatic results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Chromatic Visual Testing')
            );
            
            const body = `## 🎨 Chromatic Visual Testing
            
            Visual regression testing has been completed for this PR.
            
            - **Storybook**: [View Storybook build](https://www.chromatic.com/build?appId=${{ secrets.CHROMATIC_PROJECT_TOKEN }})
            - **Changes**: Check the Chromatic dashboard for any visual changes
            - **Status**: ${process.env.CHROMATIC_BUILD_URL ? '✅ Build successful' : '⏳ Build in progress'}
            
            ${process.env.CHROMATIC_BUILD_URL ? `[View full results](${process.env.CHROMATIC_BUILD_URL})` : ''}
            `;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }