name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel in-progress runs on new pushes to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  NEXT_PUBLIC_SENTRY_DISABLED: true

jobs:
  # Job 1: Code Quality and Linting
  lint-and-format:
    name: Code Quality
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome linting
        run: bun run lint

      - name: Check TypeScript
        run: bun run typecheck

      - name: Check dependencies
        run: echo "⚠️ Dependency check temporarily disabled due to Storybook version conflicts"
        continue-on-error: true

      - name: Validate package.json
        run: |
          if ! bun --version > /dev/null 2>&1; then
            echo "❌ Bun validation failed"
            exit 1
          fi
          echo "✅ package.json and Bun are valid"

  # Job 2: Unit and Component Tests
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Storybook tests
        run: echo "⚠️ Storybook tests temporarily disabled due to package removal"
        continue-on-error: true

      - name: Upload test coverage
        uses: codecov/codecov-action@v5
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  # Job 3: Build and Deployment Test
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build
        env:
          NEXT_PUBLIC_SITE_URL: https://example.com
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy_key_for_build

      - name: Build Storybook
        run: echo "⚠️ Storybook build temporarily disabled due to package removal"
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .next/
          retention-days: 1

  # Job 4: Visual Regression Tests
  test-visual:
    name: Visual Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [build-test]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts

      - name: Run visual regression tests
        run: bun run test:visual
        continue-on-error: true
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy_key_for_tests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  # Job 5: E2E Tests
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [build-test]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run E2E tests
        run: bunx playwright test --grep-invert "visual"
        continue-on-error: true
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy_key_for_tests

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  # Job 6: Security Audit
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run security audit
        run: bun audit

      - name: Check for known vulnerabilities
        run: |
          if bun audit --audit-level moderate; then
            echo "✅ No moderate or high vulnerabilities found"
          else
            echo "⚠️ Security vulnerabilities detected"
            echo "Continuing with warning instead of failing..."
          fi

  # Job 7: Performance and Accessibility
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [build-test]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts

      - name: Start application
        run: |
          bun run start &
          sleep 10
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy_key_for_lighthouse

      - name: Run Lighthouse CI
        run: bunx lhci autorun
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 7

  # Job 8: CodeRabbit Configuration Validation
  validate-coderabbit:
    name: CodeRabbit Config
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate CodeRabbit configuration
        run: |
          if [ -f ".coderabbit.yaml" ]; then
            echo "✅ CodeRabbit configuration found"
            
            # Basic YAML validation
            if command -v yq >/dev/null 2>&1; then
              yq eval '.coderabbit' .coderabbit.yaml > /dev/null
              echo "✅ CodeRabbit YAML is valid"
            else
              echo "⚠️ yq not available, skipping YAML validation"
            fi
            
            # Check required fields
            if grep -q "reviews:" .coderabbit.yaml; then
              echo "✅ Reviews configuration found"
            else
              echo "⚠️ Reviews configuration missing"
            fi
            
            if grep -q "chat:" .coderabbit.yaml; then
              echo "✅ Chat configuration found"
            else
              echo "⚠️ Chat configuration missing"
            fi
          else
            echo "⚠️ CodeRabbit configuration not found"
            echo "💡 Consider adding .coderabbit.yaml for AI code reviews"
          fi

  # Job 9: Dependency Analysis
  dependency-analysis:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Analyze bundle size
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            bun run build:analyze
          else
            echo "Skipping bundle analysis for non-PR events"
          fi
        continue-on-error: true
        env:
          NEXT_PUBLIC_SITE_URL: https://example.com
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy_key_for_analysis

      - name: Check for unused dependencies
        run: echo "⚠️ Dependency check temporarily disabled due to Storybook version conflicts"
        continue-on-error: true

  # Job 10: Notification and Reporting
  notify-results:
    name: Notify Results
    runs-on: ubuntu-latest
    if: always() && github.event.pull_request.draft == false
    needs: [lint-and-format, test-unit, build-test, test-visual, test-e2e, security-audit, lighthouse, validate-coderabbit, dependency-analysis]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create status summary
        run: |
          echo "## 🚀 CI/CD Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Code Quality | ${{ needs.lint-and-format.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.test-unit.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Test | ${{ needs.build-test.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Visual Tests | ${{ needs.test-visual.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| E2E Tests | ${{ needs.test-e2e.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Audit | ${{ needs.security-audit.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Lighthouse | ${{ needs.lighthouse.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| CodeRabbit Config | ${{ needs.validate-coderabbit.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Dependencies | ${{ needs.dependency-analysis.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.lint-and-format.result }}" == "success" && 
                "${{ needs.test-unit.result }}" == "success" && 
                "${{ needs.build-test.result }}" == "success" && 
                "${{ needs.test-visual.result }}" == "success" && 
                "${{ needs.test-e2e.result }}" == "success" && 
                "${{ needs.security-audit.result }}" == "success" ]]; then
            echo "### 🎉 All critical checks passed!" >> $GITHUB_STEP_SUMMARY
          else
            echo "### ⚠️ Some checks failed - please review" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('CI/CD Pipeline Results')
            );
            
            const results = {
              'Code Quality': '${{ needs.lint-and-format.result }}',
              'Unit Tests': '${{ needs.test-unit.result }}',
              'Build Test': '${{ needs.build-test.result }}',
              'Visual Tests': '${{ needs.test-visual.result }}',
              'E2E Tests': '${{ needs.test-e2e.result }}',
              'Security Audit': '${{ needs.security-audit.result }}',
              'Lighthouse': '${{ needs.lighthouse.result }}',
              'CodeRabbit Config': '${{ needs.validate-coderabbit.result }}',
              'Dependencies': '${{ needs.dependency-analysis.result }}'
            };
            
            let body = `## 🚀 CI/CD Pipeline Results\n\n`;
            body += `| Job | Status |\n|-----|--------|\n`;
            
            for (const [job, result] of Object.entries(results)) {
              const status = result === 'success' ? '✅ Passed' : 
                           result === 'failure' ? '❌ Failed' : 
                           result === 'skipped' ? '⏭️ Skipped' : '⏳ Running';
              body += `| ${job} | ${status} |\n`;
            }
            
            const allPassed = Object.values(results).every(r => r === 'success' || r === 'skipped');
            body += `\n### ${allPassed ? '🎉 All checks passed!' : '⚠️ Some checks need attention'}\n`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
